return {
    require("plugins/bufferline"),
    require("plugins/colorscheme"),
    require("plugins/comment"),
    require("plugins/leap"),
    require("plugins/lualine"),
    require("plugins/maximizer"),
    require("plugins/no_config"),
    require("plugins/noice"),
    require("plugins/oil"),
    require("plugins/snacks"),
    require("plugins/telescope"),
    require("plugins/tmux"),
    require("plugins/tree"),
    require("plugins/treesitter"),
    require("plugins/zen_mode"),
}
