require("mkdnflow").setup({
    perspective = {
        priority = "current",
    },
    links = {
        conceal = true,
        transform_explicit = function (text) return text:gsub(" ", "_") end,
    },
    mappings = {
        MkdnEnter = {{"n", "v"}, "<cr>"},
        MkdnTab = false,
        MkdnSTab = false,
        MkdnNextLink = {"n", "]l"},
        MkdnPrevLink = {"n", "[l"},
        MkdnNextHeading = {"n", "]]"},
        MkdnPrevHeading = {"n", "[["},
        MkdnGoBack = false,
        MkdnGoForward = false,
        MkdnCreateLink = false,
        MkdnCreateLinkFromClipboard = {{"n", "v"}, "mp"},
        MkdnFollowLink = false,
        MkdnDestroyLink = {"n", "<A-cr>"},
        MkdnTagSpan = false,
        MkdnMoveSource = {"n", "mr"},
        MkdnYankAnchorLink = false,
        MkdnYankFileAnchorLink = false,
        MkdnIncreaseHeading = false,
        MkdnDecreaseHeading = false,
        MkdnToggleToDo = {{"n", "v"}, "mt"},
        MkdnNewListItem = false,
        MkdnNewListItemBelowInsert = false,
        MkdnNewListItemAboveInsert = false,
        MkdnExtendList = false,
        MkdnUpdateNumbering = false,
        MkdnTableNextCell = false,
        MkdnTablePrevCell = false,
        MkdnTableNextRow = false,
        MkdnTablePrevRow = false,
        MkdnTableNewRowBelow = false,
        MkdnTableNewRowAbove = false,
        MkdnTableNewColAfter = false,
        MkdnTableNewColBefore = false,
        MkdnFoldSection = false,
        MkdnUnfoldSection = false,
    }
})
