return {
    -- require("plugins/autocompletion"),
    require("plugins/colorscheme"),
    require("plugins/comment"),
    -- require("plugins/dashboard"),
    -- require("plugins/debug"),
    -- require("plugins/floaterm"),
    -- require("plugins/git"),
    -- require("plugins/harpoon"),
    -- require("plugins/julia"),
    require("plugins/leap"),
    -- require("plugins/lsp"),
    require("plugins/lualine"),
    -- require("plugins/luasnip"),
    require("plugins/markdown"),
    -- require("plugins/maximizer"),
    require("plugins/no_config"),
    require("plugins/noice"),
    -- require("plugins/oil"),
    -- require("plugins/telescope"),
    require("plugins/tmux"),
    -- require("plugins/todo_comments"),
    -- require("plugins/tree"),
    require("plugins/treesitter"),
    -- require("plugins/trouble"),
    require("plugins/zen_mode"),
}
