return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    config = function()
        local ts = require("nvim-treesitter")
        ts.setup({ install_dir = vim.fn.stdpath("data") .. "/site" })
        ts.install({
            "bash",
            "bibtex",
            "c",
            "cmake",
            "comment",
            "cpp",
            "css",
            "csv",
            "diff",
            "dockerfile",
            -- "fortan",
            "git_config",
            "git_rebase",
            "gitcommit",
            "gitignore",
            "html",
            "java",
            "javascript",
            "jq",
            "json",
            "json5",
            "just",
            "latex",
            "lua",
            "luadoc",
            "markdown",
            "markdown_inline",
            "matlab",
            "mermaid",
            "odin",
            "powershell",
            "python",
            "r",
            "rust",
            "sql",
            "tmux",
            "toml",
            "typescript",
            "typst",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
            "zig",
        })
    end,
}
