import = [
    "~/.config/alacritty/colors/linux.toml",
]

[window]
dimensions.lines = 30
dimensions.columns = 150
position = "None"  # use window manager to force centering
padding.x = 0
padding.y = 0
decorations = "None"
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[font]
# size = 8.5  # laptop
# size = 9.25  # monitor (home)
# size = 10.25  # monitor (home)
size = 12.75  # monitor (home)
# size = 13.0  # laptop
# size = 14.0  # monitor (office/home)

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
