# ==============================================================================
#   General

add_newline = false
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
${custom.git_repo}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.git_staged}\
$all"""

[character]
success_symbol = ''
error_symbol = ''

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
style = 'bold blue'

[fill]
symbol = ' '

[sudo]
style = ''
disabled = false

# ==============================================================================
#   Git

[custom.git_repo]
format = '[$output]($style) '
style = ''
when = ''' [[ "$(git config --get remote.origin.url)" != "" ]] '''
command = '''
repo_url="$(git config --get remote.origin.url)"
repo_name=$(basename "$repo_url" ".git")
if [[ "$repo_url" == *"github"* ]]; then
    repo_name="󰊤 $repo_name"
else
    repo_name="󰮠 $repo_name"
fi
echo "$repo_name"
'''

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[git_status]
format = '\[[($ahead_behind)( $all_status)]($style)'
style = ''
# ahead_behind
ahead = '[󰁝](bold cyan)'
behind = '[󰁅](bold cyan)'
diverged = '[󰹹](bold cyan)'
up_to_date = '[=](bold cyan)'
# all_status
conflicted = '[󰖓 ](bold red)'
stashed = '[\$](bold black)'
deleted = '[✘](bold black)'
renamed = '[»](bold black)'
modified = '[!](bold red)'
typechanged = '[«](bold black)'
staged = ''
untracked = '[?](bold yellow)'

[custom.git_staged]
format = '[( $output)]($style)\] '
style = 'bold green'
when = ''
command = '''
staged=""
if git status --porcelain | grep -E '^(A  |AD |AM |D  |M  |R  |RD )' > /dev/null; then
    staged="+"
fi
echo "$staged"
'''

# ==============================================================================
#   Languages

[c]
disabled = true

[cmake]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[perl]
disabled = true

[python]
format = '[($symbol$virtualenv )]($style)'
