[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#b2b2b2"
dim_foreground = "#656565"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#b2b2b2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#b2b2b2"

[colors.normal]
black = "#000000"
red = "#b21818"
green = "#18b218"
yellow = "#b26818"
blue = "#1818b2"
magenta = "#b218b2"
cyan = "#18b2b2"
white = "#b2b2b2"

[colors.bright]
black = "#686868"
red = "#ff5454"
green = "#54ff54"
yellow = "#ffff54"
blue = "#5454ff"
magenta = "#ff54ff"
cyan = "#54ffff"
white = "#ffffff"

[colors.dim]
black = "#181818"
red = "#650000"
green = "#006500"
yellow = "#655e00"
blue = "#000065"
magenta = "#650065"
cyan = "#006565"
white = "#656565"
